### ISSUE TITLE
nghttp3 v1 release plan

### ISSUE THREAD

**Issue by tatsuhiro-t** [ngtcp2/nghttp3#144]
## Prerequisites

There is no outstanding issues that blocks nghttp3 v1.

## Changes required on v1 release

TBD

## Release schedule

- v0.12: regular release as usual
- v0.13: this release should be considered as Release Candidate (RC) 1.

**Comment by tatsuhiro-t** [comment]
At the moment, we have no blocking issues for v1. The next release will be v1, and scheduled for early or mid October.

**Comment by Lekensteyn** [comment]
Do you plan to bump the soname version, or will it maintain the same API/ABI? Currently the soname version is 9.0.0 since nghttp3 0.15.0:
https://github.com/ngtcp2/nghttp3/blob/c5b51a8b8d9123d48775f2ecb1cee710bbf2df2e/CMakeLists.txt#L30-L34

I am looking at suggesting a `libnghttp3` Homebrew formula for macOS to enable QPACK in Wireshark for improved HTTP/3 dissection. Can we ship libnghttp3 0.15.0, or should we wait for 1.0.0?

An alternative is switching to an [alternative QPACK implementation](https://gitlab.com/wireshark/wireshark/-/issues/19319) for Wireshark, but that is more work at the moment.

**Comment by tatsuhiro-t** [comment]
I do not plan to bump so version because there is no breaking changes in public API.

**Comment by tatsuhiro-t** [comment]
nghttp3 v1.0.0 is out now.
