### ISSUE TITLE
Runtime selectable QPACK static tables

### ISSUE THREAD

**Issue by samhurst** [ngtcp2/nghttp3#149]
Hello Tatsuhiro,

I would like to reuse the nghttp3 QPACK encoder/decoder with another transport protocol that is similar to H3 but uses a different static table. I've had a look, and while the mkstatichdtbl.py utility exists, I think the only use for that would be to replace the existing QPACK static table code and compile it in.

Would there be any interest in adding support for a selectable or fully custom static table when initialising the QPACK encoder or decoder? Maybe with an extended version of `nghttp3_qpack_encoder_new` which takes the application-supplied static table as an argument.

**Comment by tatsuhiro-t** [comment]
The primary use of mkstatichdtbl.py is construct static table in C from draft, because doing it manually is tedious and error prune.
While it might have some use cases for non-HTTP/3 world, for now I would like to make it out of scope for our v1 API set because I'd like to keep nghttp3 as small as possible and just works with the only HTTP/3.  But we might revisit it later if it is particularly useful.
