### ISSUE TITLE
Getting more data to a stream than we can currently deal with

### ISSUE THREAD

**Issue by bagder** [ngtcp2/nghttp3#20]
In the curl issue https://github.com/curl/curl/issues/4525, we're wrestling with the problem of having a fixed size buffer for HTTP/3 transfers and we might get more data in the `nghttp3_recv_data` than what currently fits in our buffer (because our buffer hasn't been drained yet by the consumer of our API).

With nghttp2, we can return a "pause" signal that made it possible for us to drain the buffer and then continue getting data and I think we will appreciate something like that here as well. Or possibly a way for us to say that "we received X bytes out of the N bytes delivered", and then be able to get the remaining part in a subsequent invoke. Or something.

We can reduce the risk of this happening by using a larger buffer, but we still risk that a high speed transfer can (occasionally) fill the buffer faster than the libcurl user drains it.

Thoughts?

**Comment by tatsuhiro-t** [comment]
It might be simpler if libcurl buffers stream data as needed.  Then it can use its buffer implementation which is optimized for its use.  Since libcurl is committed to receive the amount of stream data set in stream window, I think it is reasonable to expect that it can hold those amount of data in its memory.
As for header fields, nghttp3 passes it in nghttp3_rcbuf, which is reference counted buffer.  So libcurl increases its reference count and caches it without serializing it in HTTP/1.1 style, which reduces some memory overhead.

**Comment by bagder** [comment]
> It might be simpler if libcurl buffers stream data as needed.

Exactly how much data do you think it should buffer then? Because whatever amount, I can think of a way where the existing nghttp3 API will overflow that buffer and right now the only two ways I can deal with that is: 1) return error or 2) dynamically allocate more buffer memory.

(1) is terrible for users and (2) is terrible for performance and for the code in general. Right now we get away with it by having a large enough buffer that makes running into the limit less likely, but it won't work all the time.

I can download high speed data from the Internet and would like to offer a really big window for the server. But this huge window does not mean that I (in my library) want to buffer an entire window-size worth of data at any point in time. I also don't need that big buffers when I transfer TCP (or UDP), because the buffer will be drained tens, hundreds or thousands of times per second. I can saturate my connection with a 16K download application buffer when doing HTTP/1 transfers...

I can't set a small (as the size of my download buffer) window size because updating the window is slow so I need to enlarge the window before it goes to zero.

I basically need way to say to nghttp3 "hold it, while I take a moment to drain the buffer" or similar.

> As for header fields, nghttp3 passes it in nghttp3_rcbuf, which is reference counted buffer. So libcurl increases its reference count and caches it without serializing it in HTTP/1.1 style, which reduces some memory overhead.

I wouldn't even be so sure it is actually less overhead, but my main concern here is for huge data downloads and not for the headers.

**Comment by tatsuhiro-t** [comment]
UDP packet is not that much large (~1400), so just stop calling ngtcp2_conn_read_pkt then you don't have to buffer so much data, assuming that application keeps reading data from curl as much as possible.

Another option is set flow control window to the maximum buffer size curl can keep.
In my opinion, setting huge flow control window that application cannot buffer is not a good decision.
I'm not sure I understand the QUIC/TCP mechanisms correctly, but I think QUIC flow control window functions like TCP receive window.
TCP receive window is receiver chosen buffer size that it can hold at any given time.  TCP application can "pause" reading data from socket and uses smaller application buffer to achieve high performance because kernel TCP buffer stores the unread data in it.  While application does not allocate data in its user space, kernel allocates it on behalf of application.
On the other hand, in QUIC everything is in user space.  The buffer kernel allocated in TCP case is moved to application.
UDP still needs buffers to store incoming packets in kernel in order to avoid dropping it, so kernel buffer is not eliminated entirely, but it should be drained as quickly possible without no imposed limit (like TCP receive window).

Application should tell ngtcp2 that it drained N amount of HTTP data to give back the credit to the sender so that the buffer size is kept under flow control window.

Then goes back to the question: what is the best value for flow control window?  I don't have a good answer for this.  RFC 6349 has some interesting values for TCP RWIN: https://tools.ietf.org/html/rfc6349#section-3.3.1

I'm sorry I have no good answer here, because I haven't tested all these methods and which one performs best in terms of good balance of throughput and memory usage.

**Comment by bagder** [comment]
Thanks. I think an issue here is that for TCP and UDP, this (big) buffer is handled by the kernel so we can manage with a small one in the application. With QUIC, that buffer is either handled by the QUIC/h3 library or by the application (here: libcurl). Since we and our users are now used to talking about buffer sizes in the "old style" it is a challenge to sanely work with both approaches in the same code...
